name: Example workflow for Example Action
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: install ncc
      run: npm i -g @vercel/ncc
    - name: npm install
      run: npm install
    - name: show package.lock
      run: cat package-lock.json
    - name: Does ncc exist
      run: which ncc
    - name: Build
      run: npm run build
    - name: Greet
      uses: ohthepain/action-js-ts-example@v1.12
      with:
        who-to-greet: 'Mona the Octocat'
