name: Test example action

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ohthepain/action-js-example@main
        with:
          who-to-greet: 'Mona Bar'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
