name: Example workflow for Example Action
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build
    - name: Greet
      uses: ohthepain/action-js-ts-example@v1.12
      with:
        who-to-greet: 'Mona the Octocat'
