name: Example workflow for Example Action
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: git@github.com:ohthepain/action-js-ts-example.git
      with:
        who-to-greet: 'Mona the Octocat'
